### PR TITLE
Added support for @import "~antd....." style import that is supported by webpack

### PR DESCRIPTION
**Pull request by mzohaibqc**
@chenshuai2144  Kindly review when you feel free. Previously you were  using this in antd-pro and then unfortunately you have to use relative paths for antd :)

### CODE REVIEW

**Comment by chenshuai2144** [comment]
I packaged my less files, the same as your method.

**Comment by mzohaibqc** [comment]
@chenshuai2144 Did this code worked for you?

**Comment by mzohaibqc** [comment]
@chenshuai2144 Ignore this. I need to do some work to fix few issues. Closing this for now

**Comment by chenshuai2144** [comment]
I have solved this problem.

**Comment by mzohaibqc** [comment]
@chenshuai2144 Can you create a PR to handle that. I am working on solution that should work without changing those imports. What's your solution. Mine is work in progress.

**Comment by chenshuai2144** [comment]
https://github.com/chenshuai2144/merge-cssMoudle-less#readme

**Pull request closed without merging**
